/** Config */

module.exports = {
    FB_PAGE_TOKEN: 'YOUR_FACEBOOK_ACCESS_TOKEN',
    FB_PAGE_ID: 'YOUR_FACEBOOK_PAGE_ID',
    FB_VERIFY_TOKEN: 'YOUR_FACEBOOK_VERIFY_TOKEN',
    WIT_TOKEN: 'YOUR_WIT_SERVER_ACCESS_TOKEN',
};